### ISSUE TITLE
Compiling error on kinetic : -ldefault_plugin not found

### ISSUE THREAD

**Issue by rafagjordana** [OctoMap/octomap_rviz_plugins#19]
When compiling with ROS Kinetic with Ubuntu 16.04, the following error appears:

```
[100%] Linking CXX shared library /home/rafa/Desktop/catkin_ws/devel/lib/liboctomap_rviz_plugins.so
/usr/bin/ld: cannot find -ldefault_plugin
/usr/bin/ld: cannot find -ldefault_plugin
collect2: error: ld returned 1 exit status
```

While on Indigo, Ubuntu 14.04 it works nicely.

The fix is easy but I do not know whether it has any further implications. Just remove the `-ldefault_plugin` from line 51 in the CMakeLists.txt (I didn't a PR because there is no kinetic-devel branch yet).

Some further info: 
- [librviz_tutorial changelog](http://docs.ros.org/latest/changelogs/librviz_tutorial/changelog.html)
- [rviz issue](https://github.com/ros-visualization/rviz/issues/964)

**Comment by ahornung** [comment]
Fixed now. The `-ldefault_plugin` should not be necessary, so I also removed it in the indigo-devel branch (which is currently also the basis for jade and kinetic).

I also staged a release for kinetic as octomap_rviz_plugins, but that currently fails due to Qt4:
http://build.ros.org/job/Kbin_uxhf_uXhf__octomap_rviz_plugins__ubuntu_xenial_armhf__binary/2/console 

Did the source checkout build without problems for you?
